# Generated by Django 5.2.3 on 2025-06-24 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_materia_carpeta_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='materia',
            name='cuatrimestre',
            field=models.IntegerField(),
        ),
    ]
